version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: your_username
      RABBITMQ_DEFAULT_PASS: your_password

  order-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
