spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productservice?createDatabaseIfNotExist=true
    username: Mohamed-Harby
    password: MySql12Password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9090