spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank-service
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9090